/*
 * insuranceCodes.js - the hospital's insurance company table (736 codes).
 *
 * SOURCE OF TRUTH. Codes, names, and payer categories all come from the
 * hospital's own mapping (insurance_code_payer_categories). Nothing here is
 * inferred, so a category in this file is a statement by the hospital rather
 * than a guess by the tool - which is why, for example, Medicare supplement
 * plans sit under Commercial/Managed Care and not under Medicare.
 *
 * CODES ARE CASE-SENSITIVE. The table contains 21 pairs that differ only in
 * case and mean different payers - DCg is Humana while DCG is Lake Village
 * Rehab. Every lookup goes through util.findByCode, which matches the code
 * exactly before it will consider any fallback, and refuses rather than guesses
 * when two rows could match.
 *
 * WHAT THE CATEGORIES DRIVE
 * -------------------------
 * Medicare FFS and Medicare Advantage decide the two-midnight review list
 * (RQ_SHORT_MCR, IP_2MN_001) and the Medicare readmission subset. Only 20 codes are
 * Medicare fee-for-service and 103 are Medicare Advantage; everything else,
 * including every Medicare supplement plan, is outside those lists.
 *
 * "DO NOT USE / INACTIVE" CODES
 * -----------------------------
 * The hospital marks 163 codes inactive and files them under Other. They ship
 * DISABLED here, which is the one deliberate departure from the source file:
 * a retired code appearing on a current account is then reported as a retired
 * code (DQ_CODE_RETIRED) rather than absorbed into Other, where a coding
 * problem would be invisible. The hospital's category is kept on each row, so
 * re-enabling one in the Rules screen restores exactly the source mapping.
 */
(function (global) {
  'use strict';

  var UR = global.UR = global.UR || {};
  var PC = UR.PAYER_CATEGORY;

  UR.hospitalInsuranceCodes = [
    { code: "D4A", label: "AARP", category: PC.COMMERCIAL, enabled: true },
    { code: "DC4", label: "AARP", category: PC.COMMERCIAL, enabled: true },
    { code: "DCd", label: "AARP", category: PC.COMMERCIAL, enabled: true },
    { code: "DCe", label: "AARP", category: PC.COMMERCIAL, enabled: true },
    { code: "DN2", label: "AARP", category: PC.COMMERCIAL, enabled: true },
    { code: "DP4", label: "AARP", category: PC.COMMERCIAL, enabled: true },
    { code: "D4", label: "AARP Medicare Supplement", category: PC.COMMERCIAL, enabled: true },
    { code: "D4R", label: "AARP Medicare Supplement", category: PC.COMMERCIAL, enabled: true },
    { code: "DB4", label: "AARP Medicare Supplement", category: PC.COMMERCIAL, enabled: true },
    { code: "DS", label: "AARP Medicare Supplement", category: PC.COMMERCIAL, enabled: true },
    { code: "DBU", label: "Accordia National", category: PC.COMMERCIAL, enabled: true },
    { code: "DCU", label: "Accordia National", category: PC.COMMERCIAL, enabled: true },
    { code: "DPU", label: "Accordia National", category: PC.COMMERCIAL, enabled: true },
    { code: "DSU", label: "Accordia National", category: PC.COMMERCIAL, enabled: true },
    { code: "DU", label: "Accordia National", category: PC.COMMERCIAL, enabled: true },
    { code: "DUA", label: "Accordia National", category: PC.COMMERCIAL, enabled: true },
    { code: "DUR", label: "Accordia National", category: PC.COMMERCIAL, enabled: true },
    { code: "ECY", label: "Accordia National", category: PC.COMMERCIAL, enabled: true },
    { code: "ECZ", label: "Accordia National", category: PC.COMMERCIAL, enabled: true },
    { code: "N5A", label: "Advantra Freedom", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NC5", label: "Advantra Freedom", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "D6", label: "Aetna", category: PC.COMMERCIAL, enabled: true },
    { code: "D6A", label: "Aetna", category: PC.COMMERCIAL, enabled: true },
    { code: "D6R", label: "Aetna", category: PC.COMMERCIAL, enabled: true },
    { code: "DB6", label: "Aetna", category: PC.COMMERCIAL, enabled: true },
    { code: "DC6", label: "Aetna", category: PC.COMMERCIAL, enabled: true },
    { code: "DCh", label: "Aetna", category: PC.COMMERCIAL, enabled: true },
    { code: "DCi", label: "Aetna", category: PC.COMMERCIAL, enabled: true },
    { code: "DN1", label: "Aetna", category: PC.COMMERCIAL, enabled: true },
    { code: "DP6", label: "Aetna", category: PC.COMMERCIAL, enabled: true },
    { code: "DS6", label: "Aetna", category: PC.COMMERCIAL, enabled: true },
    { code: "MBT", label: "Aetna Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MCT", label: "Aetna Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MPT", label: "Aetna Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MST", label: "Aetna Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MT", label: "Aetna Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MTR", label: "Aetna Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "D3", label: "Ambetter of Arkansas", category: PC.COMMERCIAL, enabled: true },
    { code: "D3A", label: "Ambetter of Arkansas", category: PC.COMMERCIAL, enabled: true },
    { code: "D3R", label: "Ambetter of Arkansas", category: PC.COMMERCIAL, enabled: true },
    { code: "DB3", label: "Ambetter of Arkansas", category: PC.COMMERCIAL, enabled: true },
    { code: "DC3", label: "Ambetter of Arkansas", category: PC.COMMERCIAL, enabled: true },
    { code: "DCb", label: "Ambetter of Arkansas", category: PC.COMMERCIAL, enabled: true },
    { code: "DCc", label: "Ambetter of Arkansas", category: PC.COMMERCIAL, enabled: true },
    { code: "DP3", label: "Ambetter of Arkansas", category: PC.COMMERCIAL, enabled: true },
    { code: "DS3", label: "Ambetter of Arkansas", category: PC.COMMERCIAL, enabled: true },
    { code: "W1", label: "American Interstate Insurance", category: PC.OTHER, enabled: true },
    { code: "W1A", label: "American Interstate Insurance", category: PC.OTHER, enabled: true },
    { code: "W1R", label: "American Interstate Insurance", category: PC.OTHER, enabled: true },
    { code: "WB1", label: "American Interstate Insurance", category: PC.OTHER, enabled: true },
    { code: "WC1", label: "American Interstate Insurance", category: PC.OTHER, enabled: true },
    { code: "WC4", label: "American Interstate Insurance", category: PC.OTHER, enabled: true },
    { code: "WC5", label: "American Interstate Insurance", category: PC.OTHER, enabled: true },
    { code: "WP1", label: "American Interstate Insurance", category: PC.OTHER, enabled: true },
    { code: "WS1", label: "American Interstate Insurance", category: PC.OTHER, enabled: true },
    { code: "N6", label: "Arkansas Community Care", category: PC.MEDICAID, enabled: true },
    { code: "N6A", label: "Arkansas Community Care", category: PC.MEDICAID, enabled: true },
    { code: "NB6", label: "Arkansas Community Care", category: PC.MEDICAID, enabled: true },
    { code: "NC6", label: "Arkansas Community Care", category: PC.MEDICAID, enabled: true },
    { code: "NCN", label: "Arkansas Community Care", category: PC.MEDICAID, enabled: true },
    { code: "NCO", label: "Arkansas Community Care", category: PC.MEDICAID, enabled: true },
    { code: "NS6", label: "Arkansas Community Care", category: PC.MEDICAID, enabled: true },
    { code: "DBN", label: "Arkansas Hospice", category: PC.OTHER, enabled: true },
    { code: "DN", label: "Arkansas Hospice", category: PC.OTHER, enabled: true },
    { code: "DSN", label: "Arkansas Hospice", category: PC.OTHER, enabled: true },
    { code: "MBG", label: "Arkansas Integrated Providers HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MCG", label: "Arkansas Integrated Providers HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MG", label: "Arkansas Integrated Providers HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MGR", label: "Arkansas Integrated Providers HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MPG", label: "Arkansas Integrated Providers HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MSG", label: "Arkansas Integrated Providers HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "M3", label: "Arkansas Superior Select / Tribute", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "M3R", label: "Arkansas Superior Select / Tribute", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MB3", label: "Arkansas Superior Select / Tribute", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MC3", label: "Arkansas Superior Select / Tribute", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MP3", label: "Arkansas Superior Select / Tribute", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MS3", label: "Arkansas Superior Select / Tribute", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "N5", label: "Arkansas Superior Select / Tribute", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NB5", label: "Arkansas Superior Select / Tribute", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NP5", label: "Arkansas Superior Select / Tribute", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NRA", label: "Arkansas Superior Select / Tribute", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NS5", label: "Arkansas Superior Select / Tribute", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "ATA", label: "Arkansas Total Care", category: PC.MEDICAID, enabled: true },
    { code: "ATb", label: "Arkansas Total Care", category: PC.MEDICAID, enabled: true },
    { code: "ATN", label: "Arkansas Total Care", category: PC.MEDICAID, enabled: true },
    { code: "X4", label: "Arkansas Total Care", category: PC.MEDICAID, enabled: true },
    { code: "X4R", label: "Arkansas Total Care", category: PC.MEDICAID, enabled: true },
    { code: "XB4", label: "Arkansas Total Care", category: PC.MEDICAID, enabled: true },
    { code: "XC4", label: "Arkansas Total Care", category: PC.MEDICAID, enabled: true },
    { code: "XP4", label: "Arkansas Total Care", category: PC.MEDICAID, enabled: true },
    { code: "XS4", label: "Arkansas Total Care", category: PC.MEDICAID, enabled: true },
    { code: "B2", label: "Blue Cross Blue Shield", category: PC.COMMERCIAL, enabled: true },
    { code: "BB2", label: "Blue Cross Blue Shield", category: PC.COMMERCIAL, enabled: true },
    { code: "BBR", label: "Blue Cross Blue Shield", category: PC.COMMERCIAL, enabled: true },
    { code: "BC", label: "Blue Cross Blue Shield", category: PC.COMMERCIAL, enabled: true },
    { code: "BCI", label: "Blue Cross Blue Shield", category: PC.COMMERCIAL, enabled: true },
    { code: "BNA", label: "Blue Cross Blue Shield", category: PC.COMMERCIAL, enabled: true },
    { code: "BP", label: "Blue Cross Blue Shield", category: PC.COMMERCIAL, enabled: true },
    { code: "BP2", label: "Blue Cross Blue Shield", category: PC.COMMERCIAL, enabled: true },
    { code: "BS", label: "Blue Cross Blue Shield", category: PC.COMMERCIAL, enabled: true },
    { code: "MBD", label: "Blue Medicare HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MBQ", label: "Blue Medicare HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MCD", label: "Blue Medicare HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MCQ", label: "Blue Medicare HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MD", label: "Blue Medicare HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MDR", label: "Blue Medicare HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MPD", label: "Blue Medicare HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MPQ", label: "Blue Medicare HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MQ", label: "Blue Medicare HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MQR", label: "Blue Medicare HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MSD", label: "Blue Medicare HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MSQ", label: "Blue Medicare HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "DBM", label: "Breast Care Program", category: PC.OTHER, enabled: true },
    { code: "DCM", label: "Breast Care Program", category: PC.OTHER, enabled: true },
    { code: "DM", label: "Breast Care Program", category: PC.OTHER, enabled: true },
    { code: "DMA", label: "Breast Care Program", category: PC.OTHER, enabled: true },
    { code: "DMR", label: "Breast Care Program", category: PC.OTHER, enabled: true },
    { code: "DPM", label: "Breast Care Program", category: PC.OTHER, enabled: true },
    { code: "DSM", label: "Breast Care Program", category: PC.OTHER, enabled: true },
    { code: "ECM", label: "Breast Care Program", category: PC.OTHER, enabled: true },
    { code: "ECO", label: "Breast Care Program", category: PC.OTHER, enabled: true },
    { code: "N4A", label: "Care Improvement Plus", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NC4", label: "Care Improvement Plus", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NCJ", label: "Care Improvement Plus", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "X7", label: "CareSource PASSE", category: PC.MEDICAID, enabled: true },
    { code: "X7R", label: "CareSource PASSE", category: PC.MEDICAID, enabled: true },
    { code: "XB7", label: "CareSource PASSE", category: PC.MEDICAID, enabled: true },
    { code: "XC7", label: "CareSource PASSE", category: PC.MEDICAID, enabled: true },
    { code: "XP7", label: "CareSource PASSE", category: PC.MEDICAID, enabled: true },
    { code: "XS7", label: "CareSource PASSE", category: PC.MEDICAID, enabled: true },
    { code: "S2", label: "CHAMPVA", category: PC.OTHER, enabled: true },
    { code: "S2A", label: "CHAMPVA", category: PC.OTHER, enabled: true },
    { code: "S2R", label: "CHAMPVA", category: PC.OTHER, enabled: true },
    { code: "SB2", label: "CHAMPVA", category: PC.OTHER, enabled: true },
    { code: "SC2", label: "CHAMPVA", category: PC.OTHER, enabled: true },
    { code: "SC9", label: "CHAMPVA", category: PC.OTHER, enabled: true },
    { code: "SP2", label: "CHAMPVA", category: PC.OTHER, enabled: true },
    { code: "SPA", label: "CHAMPVA", category: PC.OTHER, enabled: true },
    { code: "SS2", label: "CHAMPVA", category: PC.OTHER, enabled: true },
    { code: "DBD", label: "Cigna", category: PC.COMMERCIAL, enabled: true },
    { code: "DCD", label: "Cigna", category: PC.COMMERCIAL, enabled: true },
    { code: "DCu", label: "Cigna", category: PC.COMMERCIAL, enabled: true },
    { code: "DCv", label: "Cigna", category: PC.COMMERCIAL, enabled: true },
    { code: "DD", label: "Cigna", category: PC.COMMERCIAL, enabled: true },
    { code: "DDA", label: "Cigna", category: PC.COMMERCIAL, enabled: true },
    { code: "DDR", label: "Cigna", category: PC.COMMERCIAL, enabled: true },
    { code: "DPD", label: "Cigna", category: PC.COMMERCIAL, enabled: true },
    { code: "DPN", label: "Cigna", category: PC.COMMERCIAL, enabled: true },
    { code: "DSD", label: "Cigna", category: PC.COMMERCIAL, enabled: true },
    { code: "DB", label: "Cigna Medicare Supplement", category: PC.COMMERCIAL, enabled: true },
    { code: "DBB", label: "Cigna Medicare Supplement", category: PC.COMMERCIAL, enabled: true },
    { code: "DBE", label: "Cigna Medicare Supplement", category: PC.COMMERCIAL, enabled: true },
    { code: "DCE", label: "Cigna Medicare Supplement", category: PC.COMMERCIAL, enabled: true },
    { code: "DE", label: "Cigna Medicare Supplement", category: PC.COMMERCIAL, enabled: true },
    { code: "DNA", label: "Cigna Medicare Supplement", category: PC.COMMERCIAL, enabled: true },
    { code: "DPB", label: "Cigna Medicare Supplement", category: PC.COMMERCIAL, enabled: true },
    { code: "DPE", label: "Cigna Medicare Supplement", category: PC.COMMERCIAL, enabled: true },
    { code: "DSB", label: "Cigna Medicare Supplement", category: PC.COMMERCIAL, enabled: true },
    { code: "DSE", label: "Cigna Medicare Supplement", category: PC.COMMERCIAL, enabled: true },
    { code: "C", label: "Commercial", category: PC.COMMERCIAL, enabled: true },
    { code: "CB", label: "Commercial", category: PC.COMMERCIAL, enabled: true },
    { code: "CBA", label: "Commercial", category: PC.COMMERCIAL, enabled: true },
    { code: "CBR", label: "Commercial", category: PC.COMMERCIAL, enabled: true },
    { code: "CC", label: "Commercial", category: PC.COMMERCIAL, enabled: true },
    { code: "CP", label: "Commercial", category: PC.COMMERCIAL, enabled: true },
    { code: "CS", label: "Commercial", category: PC.COMMERCIAL, enabled: true },
    { code: "DBJ", label: "CoreSource", category: PC.COMMERCIAL, enabled: true },
    { code: "DCJ", label: "CoreSource", category: PC.COMMERCIAL, enabled: true },
    { code: "DJ", label: "CoreSource", category: PC.COMMERCIAL, enabled: true },
    { code: "DJA", label: "CoreSource", category: PC.COMMERCIAL, enabled: true },
    { code: "DJR", label: "CoreSource", category: PC.COMMERCIAL, enabled: true },
    { code: "DPJ", label: "CoreSource", category: PC.COMMERCIAL, enabled: true },
    { code: "DSJ", label: "CoreSource", category: PC.COMMERCIAL, enabled: true },
    { code: "ECF", label: "CoreSource", category: PC.COMMERCIAL, enabled: true },
    { code: "ECG", label: "CoreSource", category: PC.COMMERCIAL, enabled: true },
    { code: "DBF", label: "Disability Determination", category: PC.OTHER, enabled: true },
    { code: "DCF", label: "Disability Determination", category: PC.OTHER, enabled: true },
    { code: "DCw", label: "Disability Determination", category: PC.OTHER, enabled: true },
    { code: "DCx", label: "Disability Determination", category: PC.OTHER, enabled: true },
    { code: "DF", label: "Disability Determination", category: PC.OTHER, enabled: true },
    { code: "DFA", label: "Disability Determination", category: PC.OTHER, enabled: true },
    { code: "DFR", label: "Disability Determination", category: PC.OTHER, enabled: true },
    { code: "DPF", label: "Disability Determination", category: PC.OTHER, enabled: true },
    { code: "DSF", label: "Disability Determination", category: PC.OTHER, enabled: true },
    { code: "0", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "ABT", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "APT", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "AT", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "ATC", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "ATR", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "ATS", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "B", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "B1", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "B1A", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "B1R", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "B2R", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "B3", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "B3R", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "B4", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "B4R", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "B5", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "B5R", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "B6", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "B6A", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "B6R", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "B7", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "B7A", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "B7R", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BB", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BB1", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BB3", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BB4", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BB5", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BB6", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BB7", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BBA", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BC1", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BC2", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BC3", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BC4", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BC5", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BC6", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BC7", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BC8", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BC9", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BCA", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BCB", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BCC", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BCD", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BCE", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BCF", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BCG", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BCH", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BCJ", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BCK", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BCL", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BCM", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BCN", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BCS", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BEC", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BH", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BNP", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BP1", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BP6", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BP7", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BS1", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BS6", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "BS7", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "CC1", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "CC2", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "CCB", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "CCC", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "CCD", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "CH", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "CNP", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "EBH", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "EH", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "EHC", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "EHR", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "EHS", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "EPH", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "GBA", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "M1", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "M1A", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "M1R", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "M2A", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "M2R", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "M3A", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "M4A", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "M5A", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "M6A", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "M7A", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "M8A", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "M9", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "M9A", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "M9R", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MB1", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MB9", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MBP", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MC0", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MC2", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MCa", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MCA", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MCB", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MCI", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MCJ", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MCK", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MCL", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MCM", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MCN", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MCO", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MCU", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MCW", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MCX", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MCY", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MCZ", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MEC", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MH", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MS1", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "MS9", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "N1R", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "N2R", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "N3R", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "N4", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "N4R", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "N5R", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "N6R", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "NB", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "NB4", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "NBR", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "NC8", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "NC9", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "NCA", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "NCD", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "NCF", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "NCG", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "NCI", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "NCK", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "NCL", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "NCM", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "NCQ", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "NP1", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "NP2", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "NP6", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "PRI", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "S1R", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "SBC", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "SBU", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "SPU", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "SU", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "SUC", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "SUS", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "X1R", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "X2R", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "X3", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "XC1", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "XC2", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "XC8", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "XCA", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "XCD", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "XEC", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "XH", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "XMC", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "XNP", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "XS2", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "Y", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "YS", label: "Do Not Use / Inactive", category: PC.OTHER, enabled: false },
    { code: "EBR", label: "Empower Healthcare", category: PC.MEDICAID, enabled: true },
    { code: "ECA", label: "Empower Healthcare", category: PC.MEDICAID, enabled: true },
    { code: "EHA", label: "Empower Healthcare", category: PC.MEDICAID, enabled: true },
    { code: "EHb", label: "Empower Healthcare", category: PC.MEDICAID, enabled: true },
    { code: "XBE", label: "Empower Healthcare", category: PC.MEDICAID, enabled: true },
    { code: "XCE", label: "Empower Healthcare", category: PC.MEDICAID, enabled: true },
    { code: "XE", label: "Empower Healthcare", category: PC.MEDICAID, enabled: true },
    { code: "XER", label: "Empower Healthcare", category: PC.MEDICAID, enabled: true },
    { code: "XPE", label: "Empower Healthcare", category: PC.MEDICAID, enabled: true },
    { code: "XSE", label: "Empower Healthcare", category: PC.MEDICAID, enabled: true },
    { code: "DBK", label: "Farm Bureau", category: PC.COMMERCIAL, enabled: true },
    { code: "DCK", label: "Farm Bureau", category: PC.COMMERCIAL, enabled: true },
    { code: "DK", label: "Farm Bureau", category: PC.COMMERCIAL, enabled: true },
    { code: "DKA", label: "Farm Bureau", category: PC.COMMERCIAL, enabled: true },
    { code: "DKR", label: "Farm Bureau", category: PC.COMMERCIAL, enabled: true },
    { code: "DPA", label: "Farm Bureau", category: PC.COMMERCIAL, enabled: true },
    { code: "DPK", label: "Farm Bureau", category: PC.COMMERCIAL, enabled: true },
    { code: "DSK", label: "Farm Bureau", category: PC.COMMERCIAL, enabled: true },
    { code: "ECI", label: "Farm Bureau", category: PC.COMMERCIAL, enabled: true },
    { code: "ECJ", label: "Farm Bureau", category: PC.COMMERCIAL, enabled: true },
    { code: "NBA", label: "Generic Managed Care", category: PC.COMMERCIAL, enabled: true },
    { code: "NC", label: "Generic Managed Care", category: PC.COMMERCIAL, enabled: true },
    { code: "NC7", label: "Generic Managed Care", category: PC.COMMERCIAL, enabled: true },
    { code: "NS", label: "Generic Managed Care", category: PC.COMMERCIAL, enabled: true },
    { code: "DBQ", label: "Golden Rule", category: PC.COMMERCIAL, enabled: true },
    { code: "DCQ", label: "Golden Rule", category: PC.COMMERCIAL, enabled: true },
    { code: "DPP", label: "Golden Rule", category: PC.COMMERCIAL, enabled: true },
    { code: "DQ", label: "Golden Rule", category: PC.COMMERCIAL, enabled: true },
    { code: "DQA", label: "Golden Rule", category: PC.COMMERCIAL, enabled: true },
    { code: "DQR", label: "Golden Rule", category: PC.COMMERCIAL, enabled: true },
    { code: "DSQ", label: "Golden Rule", category: PC.COMMERCIAL, enabled: true },
    { code: "NB9", label: "Harmony Health", category: PC.COMMERCIAL, enabled: true },
    { code: "DBT", label: "Hospice Home Care", category: PC.OTHER, enabled: true },
    { code: "DCT", label: "Hospice Home Care", category: PC.OTHER, enabled: true },
    { code: "DPQ", label: "Hospice Home Care", category: PC.OTHER, enabled: true },
    { code: "DPT", label: "Hospice Home Care", category: PC.OTHER, enabled: true },
    { code: "DST", label: "Hospice Home Care", category: PC.OTHER, enabled: true },
    { code: "DT", label: "Hospice Home Care", category: PC.OTHER, enabled: true },
    { code: "DTA", label: "Hospice Home Care", category: PC.OTHER, enabled: true },
    { code: "DTR", label: "Hospice Home Care", category: PC.OTHER, enabled: true },
    { code: "ECW", label: "Hospice Home Care", category: PC.OTHER, enabled: true },
    { code: "ECX", label: "Hospice Home Care", category: PC.OTHER, enabled: true },
    { code: "CV", label: "HRSA COVID-19 Uninsured Program", category: PC.OTHER, enabled: true },
    { code: "CVB", label: "HRSA COVID-19 Uninsured Program", category: PC.OTHER, enabled: true },
    { code: "CVP", label: "HRSA COVID-19 Uninsured Program", category: PC.OTHER, enabled: true },
    { code: "D5", label: "Humana", category: PC.COMMERCIAL, enabled: true },
    { code: "D5A", label: "Humana", category: PC.COMMERCIAL, enabled: true },
    { code: "D5R", label: "Humana", category: PC.COMMERCIAL, enabled: true },
    { code: "DB5", label: "Humana", category: PC.COMMERCIAL, enabled: true },
    { code: "DC5", label: "Humana", category: PC.COMMERCIAL, enabled: true },
    { code: "DCf", label: "Humana", category: PC.COMMERCIAL, enabled: true },
    { code: "DCg", label: "Humana", category: PC.COMMERCIAL, enabled: true },
    { code: "DP5", label: "Humana", category: PC.COMMERCIAL, enabled: true },
    { code: "DR5", label: "Humana", category: PC.COMMERCIAL, enabled: true },
    { code: "DS5", label: "Humana", category: PC.COMMERCIAL, enabled: true },
    { code: "M7", label: "Humana Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "M7R", label: "Humana Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MB7", label: "Humana Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MC7", label: "Humana Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MP7", label: "Humana Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MS7", label: "Humana Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "D9A", label: "Komen Breast Health", category: PC.OTHER, enabled: true },
    { code: "D9R", label: "Komen Breast Health", category: PC.OTHER, enabled: true },
    { code: "DB9", label: "Komen Breast Health", category: PC.OTHER, enabled: true },
    { code: "DC9", label: "Komen Breast Health", category: PC.OTHER, enabled: true },
    { code: "DCn", label: "Komen Breast Health", category: PC.OTHER, enabled: true },
    { code: "DCo", label: "Komen Breast Health", category: PC.OTHER, enabled: true },
    { code: "DP9", label: "Komen Breast Health", category: PC.OTHER, enabled: true },
    { code: "DS9", label: "Komen Breast Health", category: PC.OTHER, enabled: true },
    { code: "DBG", label: "Lake Village Rehab", category: PC.OTHER, enabled: true },
    { code: "DBX", label: "Lake Village Rehab", category: PC.OTHER, enabled: true },
    { code: "DCG", label: "Lake Village Rehab", category: PC.OTHER, enabled: true },
    { code: "DCy", label: "Lake Village Rehab", category: PC.OTHER, enabled: true },
    { code: "DCz", label: "Lake Village Rehab", category: PC.OTHER, enabled: true },
    { code: "DG", label: "Lake Village Rehab", category: PC.OTHER, enabled: true },
    { code: "DGA", label: "Lake Village Rehab", category: PC.OTHER, enabled: true },
    { code: "DGR", label: "Lake Village Rehab", category: PC.OTHER, enabled: true },
    { code: "DPG", label: "Lake Village Rehab", category: PC.OTHER, enabled: true },
    { code: "DSG", label: "Lake Village Rehab", category: PC.OTHER, enabled: true },
    { code: "D9", label: "Louisiana Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "X9", label: "Louisiana Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "X9R", label: "Louisiana Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XB9", label: "Louisiana Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XC9", label: "Louisiana Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XP9", label: "Louisiana Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XS9", label: "Louisiana Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "X6", label: "Magnolia Health", category: PC.MEDICAID, enabled: true },
    { code: "X6A", label: "Magnolia Health", category: PC.MEDICAID, enabled: true },
    { code: "X6R", label: "Magnolia Health", category: PC.MEDICAID, enabled: true },
    { code: "X6S", label: "Magnolia Health", category: PC.MEDICAID, enabled: true },
    { code: "XB6", label: "Magnolia Health", category: PC.MEDICAID, enabled: true },
    { code: "XC6", label: "Magnolia Health", category: PC.MEDICAID, enabled: true },
    { code: "XP6", label: "Magnolia Health", category: PC.MEDICAID, enabled: true },
    { code: "XS6", label: "Magnolia Health", category: PC.MEDICAID, enabled: true },
    { code: "X", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "X1", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "X1A", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "X2", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "X3A", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "X3R", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XB", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XB1", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "Xb1", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XB2", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XB3", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XBA", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XBR", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XC", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XC3", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XCR", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XP", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XP1", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XP2", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XP3", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XP8", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XS", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XS1", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XS3", label: "Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "M", label: "Medicare", category: PC.MEDICARE_FFS, enabled: true },
    { code: "M2", label: "Medicare", category: PC.MEDICARE_FFS, enabled: true },
    { code: "MB", label: "Medicare", category: PC.MEDICARE_FFS, enabled: true },
    { code: "Mb1", label: "Medicare", category: PC.MEDICARE_FFS, enabled: true },
    { code: "MB2", label: "Medicare", category: PC.MEDICARE_FFS, enabled: true },
    { code: "MBA", label: "Medicare", category: PC.MEDICARE_FFS, enabled: true },
    { code: "MBR", label: "Medicare", category: PC.MEDICARE_FFS, enabled: true },
    { code: "MC", label: "Medicare", category: PC.MEDICARE_FFS, enabled: true },
    { code: "MC9", label: "Medicare", category: PC.MEDICARE_FFS, enabled: true },
    { code: "MNP", label: "Medicare", category: PC.MEDICARE_FFS, enabled: true },
    { code: "MP", label: "Medicare", category: PC.MEDICARE_FFS, enabled: true },
    { code: "MP2", label: "Medicare", category: PC.MEDICARE_FFS, enabled: true },
    { code: "MPB", label: "Medicare", category: PC.MEDICARE_FFS, enabled: true },
    { code: "MPP", label: "Medicare", category: PC.MEDICARE_FFS, enabled: true },
    { code: "MS", label: "Medicare", category: PC.MEDICARE_FFS, enabled: true },
    { code: "MS2", label: "Medicare", category: PC.MEDICARE_FFS, enabled: true },
    { code: "N1A", label: "Medicare Advantage HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NC1", label: "Medicare Advantage HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "WAO", label: "Midwest Insurance Co.", category: PC.OTHER, enabled: true },
    { code: "WAR", label: "Midwest Insurance Co.", category: PC.OTHER, enabled: true },
    { code: "WI", label: "Midwest Insurance Co.", category: PC.OTHER, enabled: true },
    { code: "X5", label: "Mississippi Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "X5A", label: "Mississippi Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "X5R", label: "Mississippi Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "X5S", label: "Mississippi Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XB5", label: "Mississippi Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XC5", label: "Mississippi Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XD", label: "Mississippi Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XD2", label: "Mississippi Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XDC", label: "Mississippi Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XP5", label: "Mississippi Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XS5", label: "Mississippi Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "XSF", label: "Mississippi Medicaid", category: PC.MEDICAID, enabled: true },
    { code: "X9S", label: "MississippiCAN / UHC", category: PC.MEDICAID, enabled: true },
    { code: "XBM", label: "MississippiCAN / UHC", category: PC.MEDICAID, enabled: true },
    { code: "XCM", label: "MississippiCAN / UHC", category: PC.MEDICAID, enabled: true },
    { code: "XM", label: "MississippiCAN / UHC", category: PC.MEDICAID, enabled: true },
    { code: "XMR", label: "MississippiCAN / UHC", category: PC.MEDICAID, enabled: true },
    { code: "XMS", label: "MississippiCAN / UHC", category: PC.MEDICAID, enabled: true },
    { code: "XPM", label: "MississippiCAN / UHC", category: PC.MEDICAID, enabled: true },
    { code: "XD1", label: "Molina Healthcare Mississippi", category: PC.MEDICAID, enabled: true },
    { code: "D7", label: "Municipal Health Benefit", category: PC.COMMERCIAL, enabled: true },
    { code: "D7A", label: "Municipal Health Benefit", category: PC.COMMERCIAL, enabled: true },
    { code: "D7R", label: "Municipal Health Benefit", category: PC.COMMERCIAL, enabled: true },
    { code: "DB7", label: "Municipal Health Benefit", category: PC.COMMERCIAL, enabled: true },
    { code: "DC7", label: "Municipal Health Benefit", category: PC.COMMERCIAL, enabled: true },
    { code: "DCj", label: "Municipal Health Benefit", category: PC.COMMERCIAL, enabled: true },
    { code: "DCk", label: "Municipal Health Benefit", category: PC.COMMERCIAL, enabled: true },
    { code: "DP7", label: "Municipal Health Benefit", category: PC.COMMERCIAL, enabled: true },
    { code: "DPC", label: "Municipal Health Benefit", category: PC.COMMERCIAL, enabled: true },
    { code: "DS7", label: "Municipal Health Benefit", category: PC.COMMERCIAL, enabled: true },
    { code: "DBO", label: "Mutual of Omaha", category: PC.COMMERCIAL, enabled: true },
    { code: "DCO", label: "Mutual of Omaha", category: PC.COMMERCIAL, enabled: true },
    { code: "DN4", label: "Mutual of Omaha", category: PC.COMMERCIAL, enabled: true },
    { code: "DO", label: "Mutual of Omaha", category: PC.COMMERCIAL, enabled: true },
    { code: "DOA", label: "Mutual of Omaha", category: PC.COMMERCIAL, enabled: true },
    { code: "DOR", label: "Mutual of Omaha", category: PC.COMMERCIAL, enabled: true },
    { code: "DPO", label: "Mutual of Omaha", category: PC.COMMERCIAL, enabled: true },
    { code: "DSO", label: "Mutual of Omaha", category: PC.COMMERCIAL, enabled: true },
    { code: "ECQ", label: "Mutual of Omaha", category: PC.COMMERCIAL, enabled: true },
    { code: "ECT", label: "Mutual of Omaha", category: PC.COMMERCIAL, enabled: true },
    { code: "MC1", label: "Palmetto GBA (Medicare)", category: PC.MEDICARE_FFS, enabled: true },
    { code: "MCF", label: "Palmetto GBA (Medicare)", category: PC.MEDICARE_FFS, enabled: true },
    { code: "MP1", label: "Palmetto GBA (Medicare)", category: PC.MEDICARE_FFS, enabled: true },
    { code: "MPN", label: "Palmetto GBA (Medicare)", category: PC.MEDICARE_FFS, enabled: true },
    { code: "DBV", label: "Physicians Mutual", category: PC.COMMERCIAL, enabled: true },
    { code: "DCV", label: "Physicians Mutual", category: PC.COMMERCIAL, enabled: true },
    { code: "DPR", label: "Physicians Mutual", category: PC.COMMERCIAL, enabled: true },
    { code: "DPV", label: "Physicians Mutual", category: PC.COMMERCIAL, enabled: true },
    { code: "DSV", label: "Physicians Mutual", category: PC.COMMERCIAL, enabled: true },
    { code: "DV", label: "Physicians Mutual", category: PC.COMMERCIAL, enabled: true },
    { code: "DVA", label: "Physicians Mutual", category: PC.COMMERCIAL, enabled: true },
    { code: "DVR", label: "Physicians Mutual", category: PC.COMMERCIAL, enabled: true },
    { code: "EC1", label: "Physicians Mutual", category: PC.COMMERCIAL, enabled: true },
    { code: "EC2", label: "Physicians Mutual", category: PC.COMMERCIAL, enabled: true },
    { code: "M5", label: "Primewell", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "M5R", label: "Primewell", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MB5", label: "Primewell", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MC5", label: "Primewell", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MP5", label: "Primewell", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MS5", label: "Primewell", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "P", label: "Private Pay", category: PC.SELF_PAY, enabled: true },
    { code: "D2", label: "QualChoice", category: PC.COMMERCIAL, enabled: true },
    { code: "D2A", label: "QualChoice", category: PC.COMMERCIAL, enabled: true },
    { code: "D2R", label: "QualChoice", category: PC.COMMERCIAL, enabled: true },
    { code: "DB2", label: "QualChoice", category: PC.COMMERCIAL, enabled: true },
    { code: "DC2", label: "QualChoice", category: PC.COMMERCIAL, enabled: true },
    { code: "DCa", label: "QualChoice", category: PC.COMMERCIAL, enabled: true },
    { code: "DCZ", label: "QualChoice", category: PC.COMMERCIAL, enabled: true },
    { code: "DN7", label: "QualChoice", category: PC.COMMERCIAL, enabled: true },
    { code: "DP2", label: "QualChoice", category: PC.COMMERCIAL, enabled: true },
    { code: "DS2", label: "QualChoice", category: PC.COMMERCIAL, enabled: true },
    { code: "M8", label: "Shared Health Mississippi HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "M8R", label: "Shared Health Mississippi HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MB8", label: "Shared Health Mississippi HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MC8", label: "Shared Health Mississippi HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MP8", label: "Shared Health Mississippi HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MS8", label: "Shared Health Mississippi HMO", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "DBW", label: "State Farm Insurance", category: PC.OTHER, enabled: true },
    { code: "DCW", label: "State Farm Insurance", category: PC.OTHER, enabled: true },
    { code: "DPS", label: "State Farm Insurance", category: PC.OTHER, enabled: true },
    { code: "DPW", label: "State Farm Insurance", category: PC.OTHER, enabled: true },
    { code: "DSW", label: "State Farm Insurance", category: PC.OTHER, enabled: true },
    { code: "DW", label: "State Farm Insurance", category: PC.OTHER, enabled: true },
    { code: "DWA", label: "State Farm Insurance", category: PC.OTHER, enabled: true },
    { code: "DWR", label: "State Farm Insurance", category: PC.OTHER, enabled: true },
    { code: "EC3", label: "State Farm Insurance", category: PC.OTHER, enabled: true },
    { code: "EC4", label: "State Farm Insurance", category: PC.OTHER, enabled: true },
    { code: "N2", label: "Sterling Option II", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "N2A", label: "Sterling Option II", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NB2", label: "Sterling Option II", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NC2", label: "Sterling Option II", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NS2", label: "Sterling Option II", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "SPC", label: "Summit Community Care", category: PC.MEDICAID, enabled: true },
    { code: "SUA", label: "Summit Community Care", category: PC.MEDICAID, enabled: true },
    { code: "SUb", label: "Summit Community Care", category: PC.MEDICAID, enabled: true },
    { code: "SUR", label: "Summit Community Care", category: PC.MEDICAID, enabled: true },
    { code: "XBF", label: "Summit Community Care", category: PC.MEDICAID, enabled: true },
    { code: "XCF", label: "Summit Community Care", category: PC.MEDICAID, enabled: true },
    { code: "XF", label: "Summit Community Care", category: PC.MEDICAID, enabled: true },
    { code: "XFR", label: "Summit Community Care", category: PC.MEDICAID, enabled: true },
    { code: "XPF", label: "Summit Community Care", category: PC.MEDICAID, enabled: true },
    { code: "S", label: "TRICARE / CHAMPUS", category: PC.OTHER, enabled: true },
    { code: "S3", label: "TRICARE / CHAMPUS", category: PC.OTHER, enabled: true },
    { code: "S3A", label: "TRICARE / CHAMPUS", category: PC.OTHER, enabled: true },
    { code: "S3R", label: "TRICARE / CHAMPUS", category: PC.OTHER, enabled: true },
    { code: "SB", label: "TRICARE / CHAMPUS", category: PC.OTHER, enabled: true },
    { code: "SB3", label: "TRICARE / CHAMPUS", category: PC.OTHER, enabled: true },
    { code: "SBA", label: "TRICARE / CHAMPUS", category: PC.OTHER, enabled: true },
    { code: "SBR", label: "TRICARE / CHAMPUS", category: PC.OTHER, enabled: true },
    { code: "SC", label: "TRICARE / CHAMPUS", category: PC.OTHER, enabled: true },
    { code: "SC3", label: "TRICARE / CHAMPUS", category: PC.OTHER, enabled: true },
    { code: "SC5", label: "TRICARE / CHAMPUS", category: PC.OTHER, enabled: true },
    { code: "SC6", label: "TRICARE / CHAMPUS", category: PC.OTHER, enabled: true },
    { code: "SCA", label: "TRICARE / CHAMPUS", category: PC.OTHER, enabled: true },
    { code: "SCD", label: "TRICARE / CHAMPUS", category: PC.OTHER, enabled: true },
    { code: "SCF", label: "TRICARE / CHAMPUS", category: PC.OTHER, enabled: true },
    { code: "SP", label: "TRICARE / CHAMPUS", category: PC.OTHER, enabled: true },
    { code: "SS", label: "TRICARE / CHAMPUS", category: PC.OTHER, enabled: true },
    { code: "S5", label: "TRICARE East", category: PC.OTHER, enabled: true },
    { code: "SB5", label: "TRICARE East", category: PC.OTHER, enabled: true },
    { code: "SC1", label: "TRICARE East", category: PC.OTHER, enabled: true },
    { code: "SS3", label: "TRICARE East", category: PC.OTHER, enabled: true },
    { code: "S4", label: "TRICARE for Life", category: PC.OTHER, enabled: true },
    { code: "S4A", label: "TRICARE for Life", category: PC.OTHER, enabled: true },
    { code: "S4R", label: "TRICARE for Life", category: PC.OTHER, enabled: true },
    { code: "SB4", label: "TRICARE for Life", category: PC.OTHER, enabled: true },
    { code: "SC4", label: "TRICARE for Life", category: PC.OTHER, enabled: true },
    { code: "SCG", label: "TRICARE for Life", category: PC.OTHER, enabled: true },
    { code: "SCI", label: "TRICARE for Life", category: PC.OTHER, enabled: true },
    { code: "SP4", label: "TRICARE for Life", category: PC.OTHER, enabled: true },
    { code: "SP5", label: "TRICARE for Life", category: PC.OTHER, enabled: true },
    { code: "SS4", label: "TRICARE for Life", category: PC.OTHER, enabled: true },
    { code: "TBW", label: "TRICARE West", category: PC.OTHER, enabled: true },
    { code: "TCW", label: "TRICARE West", category: PC.OTHER, enabled: true },
    { code: "TPW", label: "TRICARE West", category: PC.OTHER, enabled: true },
    { code: "TSW", label: "TRICARE West", category: PC.OTHER, enabled: true },
    { code: "TW", label: "TRICARE West", category: PC.OTHER, enabled: true },
    { code: "TWR", label: "TRICARE West", category: PC.OTHER, enabled: true },
    { code: "D8", label: "UMR / United Medical Resources", category: PC.COMMERCIAL, enabled: true },
    { code: "D8A", label: "UMR / United Medical Resources", category: PC.COMMERCIAL, enabled: true },
    { code: "D8R", label: "UMR / United Medical Resources", category: PC.COMMERCIAL, enabled: true },
    { code: "DA", label: "UMR / United Medical Resources", category: PC.COMMERCIAL, enabled: true },
    { code: "DAA", label: "UMR / United Medical Resources", category: PC.COMMERCIAL, enabled: true },
    { code: "DAR", label: "UMR / United Medical Resources", category: PC.COMMERCIAL, enabled: true },
    { code: "DB8", label: "UMR / United Medical Resources", category: PC.COMMERCIAL, enabled: true },
    { code: "DBA", label: "UMR / United Medical Resources", category: PC.COMMERCIAL, enabled: true },
    { code: "DC8", label: "UMR / United Medical Resources", category: PC.COMMERCIAL, enabled: true },
    { code: "DCA", label: "UMR / United Medical Resources", category: PC.COMMERCIAL, enabled: true },
    { code: "DCl", label: "UMR / United Medical Resources", category: PC.COMMERCIAL, enabled: true },
    { code: "DCm", label: "UMR / United Medical Resources", category: PC.COMMERCIAL, enabled: true },
    { code: "DCR", label: "UMR / United Medical Resources", category: PC.COMMERCIAL, enabled: true },
    { code: "DCs", label: "UMR / United Medical Resources", category: PC.COMMERCIAL, enabled: true },
    { code: "DCt", label: "UMR / United Medical Resources", category: PC.COMMERCIAL, enabled: true },
    { code: "DP8", label: "UMR / United Medical Resources", category: PC.COMMERCIAL, enabled: true },
    { code: "DS8", label: "UMR / United Medical Resources", category: PC.COMMERCIAL, enabled: true },
    { code: "DSA", label: "UMR / United Medical Resources", category: PC.COMMERCIAL, enabled: true },
    { code: "DBI", label: "Union Pacific Health Plan", category: PC.COMMERCIAL, enabled: true },
    { code: "DCI", label: "Union Pacific Health Plan", category: PC.COMMERCIAL, enabled: true },
    { code: "DI", label: "Union Pacific Health Plan", category: PC.COMMERCIAL, enabled: true },
    { code: "DIA", label: "Union Pacific Health Plan", category: PC.COMMERCIAL, enabled: true },
    { code: "DIR", label: "Union Pacific Health Plan", category: PC.COMMERCIAL, enabled: true },
    { code: "DPI", label: "Union Pacific Health Plan", category: PC.COMMERCIAL, enabled: true },
    { code: "DPY", label: "Union Pacific Health Plan", category: PC.COMMERCIAL, enabled: true },
    { code: "DSI", label: "Union Pacific Health Plan", category: PC.COMMERCIAL, enabled: true },
    { code: "ECD", label: "Union Pacific Health Plan", category: PC.COMMERCIAL, enabled: true },
    { code: "D1", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "D1A", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "D1R", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "DB1", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "DBL", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "DC1", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "DCL", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "DCX", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "DCY", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "DL", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "DLA", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "DLR", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "DN5", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "DP1", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "DPL", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "DPZ", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "DS1", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "DSL", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "ECK", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "ECL", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "N1P", label: "UnitedHealthcare", category: PC.COMMERCIAL, enabled: true },
    { code: "M4", label: "UnitedHealthcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "M4R", label: "UnitedHealthcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MB4", label: "UnitedHealthcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MC4", label: "UnitedHealthcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MP4", label: "UnitedHealthcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MP9", label: "UnitedHealthcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MS4", label: "UnitedHealthcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "N1", label: "UnitedHealthcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NB1", label: "UnitedHealthcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NPN", label: "UnitedHealthcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NPP", label: "UnitedHealthcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NRI", label: "UnitedHealthcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NS1", label: "UnitedHealthcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "S1", label: "VA Community Care", category: PC.OTHER, enabled: true },
    { code: "S1A", label: "VA Community Care", category: PC.OTHER, enabled: true },
    { code: "S6", label: "VA Community Care", category: PC.OTHER, enabled: true },
    { code: "S6R", label: "VA Community Care", category: PC.OTHER, enabled: true },
    { code: "SB1", label: "VA Community Care", category: PC.OTHER, enabled: true },
    { code: "SB6", label: "VA Community Care", category: PC.OTHER, enabled: true },
    { code: "SC7", label: "VA Community Care", category: PC.OTHER, enabled: true },
    { code: "SC8", label: "VA Community Care", category: PC.OTHER, enabled: true },
    { code: "SP1", label: "VA Community Care", category: PC.OTHER, enabled: true },
    { code: "SP6", label: "VA Community Care", category: PC.OTHER, enabled: true },
    { code: "SP7", label: "VA Community Care", category: PC.OTHER, enabled: true },
    { code: "SS1", label: "VA Community Care", category: PC.OTHER, enabled: true },
    { code: "SS6", label: "VA Community Care", category: PC.OTHER, enabled: true },
    { code: "NP4", label: "Vantage Health Plan", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NP7", label: "Vantage Health Plan", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NR8", label: "Vantage Health Plan", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NS4", label: "Vantage Health Plan", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "M6", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "M6R", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MB6", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MBV", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MC6", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MCV", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MP6", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MPV", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MS6", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MSV", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MV", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "MVR", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "N3", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "N3A", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "N8R", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NB3", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NP", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NP3", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NP8", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NS3", label: "Wellcare Medicare Advantage", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "NC3", label: "Windsor Health Plan", category: PC.MEDICARE_ADVANTAGE, enabled: true },
    { code: "W", label: "Workers' Compensation", category: PC.OTHER, enabled: true },
    { code: "W2", label: "Workers' Compensation", category: PC.OTHER, enabled: true },
    { code: "W2A", label: "Workers' Compensation", category: PC.OTHER, enabled: true },
    { code: "W2R", label: "Workers' Compensation", category: PC.OTHER, enabled: true },
    { code: "WB", label: "Workers' Compensation", category: PC.OTHER, enabled: true },
    { code: "WB2", label: "Workers' Compensation", category: PC.OTHER, enabled: true },
    { code: "WBR", label: "Workers' Compensation", category: PC.OTHER, enabled: true },
    { code: "WC", label: "Workers' Compensation", category: PC.OTHER, enabled: true },
    { code: "WC2", label: "Workers' Compensation", category: PC.OTHER, enabled: true },
    { code: "WC3", label: "Workers' Compensation", category: PC.OTHER, enabled: true },
    { code: "WP", label: "Workers' Compensation", category: PC.OTHER, enabled: true },
    { code: "WS", label: "Workers' Compensation", category: PC.OTHER, enabled: true },
    { code: "WS2", label: "Workers' Compensation", category: PC.OTHER, enabled: true }
  ];

})(typeof globalThis !== 'undefined' ? globalThis : this);
